name: Code update PR

on:
  pull_request:
    types:
      - opened
      - synchronize
#  push:
    branches: 
      - dev/**
      - feature/**
    paths:
      - src/**
      - app/**
  workflow_dispatch:


concurrency:
 group: code-dev
 cancel-in-progress: true


jobs: 
  create_pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Create Github Apps Token
        uses: atolycs/gh-action-util/create-gha-token@main
        id: gh_token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Draft Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.gh_token.outputs.token }}
          script: |
            const sha = context.payload.pull_request?.head.sha ?? context.sha;
            const { repo, owner } = context.repo
            
            try {
              const result = await github.rest.pulls.create({
                title: '[CI] code update ${{ github.ref_name }} ',
                owner: owner,
                repo: repo,
                head: '${{ github.ref_name }}',
                base: 'main',
                body: [
                  'Code Update detected: ${{ github.ref_name }}',
                  'Auto generated by [actions/github-script](https://github.com/actions/github-script).'
                ].join('\n')
              })
              console.log(`Pull request created: ${result.data.html_url}`)
            } catch (e) {
              console.log(`${e.status} - Pull Request Failed: ${e.message}`)
            }

  build_preview:
    name: Build Web Page (Preview)
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Preview
        uses: atolycs/gh-action-util/deploy-cf-pages@main
        with:
          gha-app-id: ${{ secrets.APP_ID }}
          gha-app-pem: ${{ secrets.APP_PEM }}
          cf-gentoken: ${{ secrets.CF_TOKEN }}
          cf-account-id: ${{ secrets.CF_ACCOUNT_ID }}

